library(arules)
library(ggplot2)
Groceries<-read.transactions(file.choose(),sep = ",")
class(Groceries)
summary(Groceries)
inspect(Groceries[1:10])
itemFrequency(Groceries[,1])
itemFrequency(Groceries[,1:169])
itemFrequencyPlot(Groceries, support=0.15)
itemFrequencyPlot(Groceries, topN =10) 
m<-apriori(Groceries)
summary(m)
m2<-apriori(Groceries,parameter = list(support=0.007,confidence=0.5))
summary(m2)
inspect(m2[1:45])
inspect(sort(m2,by="lift",decreasing =TRUE)[1:10])
inspect(m2)
m3 <- apriori(Groceries, parameter = list(support=0.007,confidence=0.2),
              appearance = list(default="rhs",lhs=c("whole milk", "soda")))
summary(m3)
inspect(m3)

library(arulesViz)
plot(m3,jitter=0)